### ISSUE TITLE
make on Mac OS doesn't seem to find julia in PATH.

### ISSUE THREAD

**Issue by timkittel** [JuliaEnergy/PowerDynBase.jl#56]
Somehow it seems that on Mac OS, `make` uses `sh` instead of `bash`. @WouterVer,  can we try to figure that out within the next days? That would make it a lot easier for you to build the docs and less work for me (:

**Comment by WouterVer** [comment]
That would be awesome, somehow I do not get: Wouters-MacBook-Pro:PowerDynBase.jl wouterverschueren$ julia -e "using Pkg; Pkg.activate(\".\"); include(\"docs/make.jl\")" to work.

**Comment by timkittel** [comment]
Haha, I tihnk you run it in the wrong directory. I will contact you in private, as this issue is public, okai?

**Comment by timkittel** [comment]
We couldn't solve it. If a person with experience with `make` under Mac OS could help, that would be asesome. @FHell ?

**Comment by FHell** [comment]
How did you try to add it to Path? .bash_profile?

**Comment by timkittel** [comment]
Actually, after your comment we tried it again. And for some reason, the shell in the terminal was finding the `julia` link, but not the make shell. Moving the link from `/usr/local/julia` to `/usr/local/bin/julia` fixed it. Thanks (:
