### ISSUE TITLE
Include Modia.jl integration

### ISSUE THREAD

**Issue by SabineAuer** [JuliaEnergy/PowerDynBase.jl#57]
According to our [discussion with Modia developers](https://github.com/ModiaSim/Modia.jl/issues/91) I want to start integrating Modia into PowerDynamics to simplify the creation of NodeDynamics. It would allow a modular development of components and defining inputs and outputs for these. Goal would be to derive the residual rhs from the component built with Modia and integrate this one into NodeDynamics.

**Comment by timkittel** [comment]
Okai, sounds great. As this is will be a huge archicetural step, we should create a separate Repo for that. What do you think about PowerDynModia.jl as name? Will you set it up?

**Comment by SabineAuer** [comment]
Yes, I will set up a new repo for that! PowerDynModia.jl sounds great.

**Comment by timkittel** [comment]
Can I close this as the discussion should be in the appropriate repo?

**Comment by SabineAuer** [comment]
Yes! Closing it is fine!
